branches:
  - main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      releaseRules:
        - type: refactor
          release: minor
        - type: chore
          release: patch
        - scope: no-release
          release: false
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: Features
            hidden: false
          - type: fix
            section: Bug Fixes
            hidden: false
          - type: style
            section: Styles
            hidden: false
          - type: refactor
            section: Refactors
            hidden: false
          - type: perf
            section: Performance Improvements
            hidden: false
          - type: revert
            section: Reverts
            hidden: false
          - type: test
            section: Tests
            hidden: true
          - type: ci
            section: Continuous Integration
            hidden: true
          - type: chore
            hidden: true
  - - "@semantic-release/changelog"
    - changelogTitle: "# CHANGELOG"
      presetConfig:
        types:
          - type: feat
            section: Features
          - type: fix
            section: Bug Fixes
          - type: style
            section: Styles
          - type: refactor
            section: Refactors
          - type: perf
            section: Performance Improvements
          - type: test
            section: Tests
          - type: ci
            section: Continuous Integration
          - type: revert
            section: Reverts
          - type: chore
            hidden: true
  - - "@semantic-release/github"
    - assets:
        - path: CHANGELOG.md
          label: CHANGELOG
