# Generated by Django 6.0 on 2026-05-31 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_activity_category_alter_activity_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["-date"],
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["id"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
