# Generated by Django 6.0 on 2026-06-20 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_activity_options_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["id"],
                "permissions": (
                    ("change_user_activities", "Can change the user's activities"),
                ),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only Arabic letters are allowed.",
                        regex="[\\u0600-\\u06FF\\s]+",
                    )
                ],
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only Arabic letters are allowed.",
                        regex="[\\u0600-\\u06FF\\s]+",
                    )
                ],
                verbose_name="last name",
            ),
        ),
    ]
