# Generated by Django 5.1.5 on 2025-07-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
