# Generated by Django 6.0 on 2026-04-30 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0002_alter_goal_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="goal",
            name="current",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="current",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="scope",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                default="monthly",
                max_length=10,
                verbose_name="scope",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="target",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="target",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
    ]
