# Generated by Django 6.0 on 2026-05-31 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0003_alter_goal_created_at_alter_goal_current_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goal",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Goal",
                "verbose_name_plural": "Goals",
            },
        ),
    ]
