# Generated by Django 5.1.5 on 2025-05-08 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_seed_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["id"], "verbose_name_plural": "Categories"},
        ),
    ]
