# Generated by Django 5.2.6 on 2026-03-23 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_category_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="name_ar",
        ),
    ]
