# Generated by Django 6.0 on 2026-04-30 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_category_name_ar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.category",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="date",
            field=models.DateTimeField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="value",
            field=models.IntegerField(verbose_name="value"),
        ),
    ]
